<?php
namespace R2Offload;

defined( 'ABSPATH' ) || exit;

/**
 * Handles uploading/deleting all files for a single attachment (original + all sizes).
 *
 * WooCommerce compatibility notes:
 *  - WooCommerce registers additional image sizes: woocommerce_thumbnail,
 *    woocommerce_single, woocommerce_gallery_thumbnail. These are generated by WP
 *    into $metadata['sizes'] like any other registered size — collect_files() picks
 *    them up automatically with no special handling needed.
 *  - WooCommerce may regenerate sizes after the initial upload (lazy generation via
 *    wc_product_maybe_generate_image_resize). On re-sync we detect which R2 keys are
 *    genuinely new (not already tracked in _r2_offload_keys) and only upload those.
 *    This avoids redundant PutObject calls on files already in R2.
 *  - filesize() is guarded: if "delete local" is enabled and a file was deleted after a
 *    previous sync, we skip it gracefully rather than throwing a warning.
 */
class AttachmentSync {

    private R2Client    $r2;
    private Settings    $settings;
    private ErrorLogger $logger;

    public function __construct( R2Client $r2, Settings $settings, ErrorLogger $logger ) {
        $this->r2       = $r2;
        $this->settings = $settings;
        $this->logger   = $logger;
    }

    /**
     * Upload all files for an attachment to R2 and update post meta.
     * On re-sync (WooCommerce size regeneration) only genuinely new files are uploaded.
     *
     * @param int $attachment_id
     * @return array{ uploaded: int, failed: int, skipped: int }
     */
    public function sync_attachment( int $attachment_id ): array {
        $result = [ 'uploaded' => 0, 'failed' => 0, 'skipped' => 0 ];

        if ( ! $this->settings->is_configured() ) {
            $this->logger->warning( 'Sync skipped: plugin not configured.', [ 'attachment_id' => $attachment_id ] );
            $result['skipped']++;
            return $result;
        }

        $metadata = wp_get_attachment_metadata( $attachment_id );
        $attached = get_post_meta( $attachment_id, '_wp_attached_file', true );

        if ( ! $attached ) {
            $this->logger->error( 'Sync failed: _wp_attached_file meta missing.', [ 'attachment_id' => $attachment_id ] );
            $result['failed']++;
            return $result;
        }

        // Check excluded MIME types.
        $mime = get_post_mime_type( $attachment_id );
        if ( $mime && in_array( $mime, $this->settings->get_excluded_mime_types(), true ) ) {
            $result['skipped']++;
            return $result;
        }

        $upload_dir  = wp_upload_dir();
        $base_dir    = trailingslashit( $upload_dir['basedir'] );
        $path_prefix = $this->settings->get_path_prefix();

        // Build the full [ local_path => r2_key ] map for this attachment.
        $all_files = $this->collect_files( $attached, $metadata, $base_dir, $path_prefix );

        // Determine which keys are already tracked (from a prior sync).
        // This lets us skip files already on R2 and only upload genuinely new ones
        // (e.g. WooCommerce sizes generated after the original upload).
        $existing_keys_json = get_post_meta( $attachment_id, '_r2_offload_keys', true );
        $existing_keys      = $existing_keys_json ? (array) json_decode( $existing_keys_json, true ) : [];
        $existing_keys_set  = array_flip( $existing_keys );

        $uploaded_keys = $existing_keys; // Carry forward what was already uploaded.
        $bytes_uploaded = 0;

        foreach ( $all_files as $local_path => $r2_key ) {
            // Skip files already confirmed in R2.
            if ( isset( $existing_keys_set[ $r2_key ] ) ) {
                $result['skipped']++;
                continue;
            }

            if ( ! file_exists( $local_path ) ) {
                // File may have been deleted by a previous "delete local" run or simply
                // not generated (e.g. WooCommerce lazy generation not triggered yet).
                $this->logger->warning( 'File missing locally, skipping.', [ 'path' => $local_path ] );
                $result['skipped']++;
                continue;
            }

            $file_mime = mime_content_type( $local_path ) ?: ( $mime ?: 'application/octet-stream' );
            $file_size = filesize( $local_path ); // safe: file_exists() checked above

            $ok = $this->r2->upload_file( $local_path, $r2_key, $file_mime );
            if ( $ok ) {
                $uploaded_keys[] = $r2_key;
                $bytes_uploaded += (int) $file_size;
                $result['uploaded']++;
            } else {
                $result['failed']++;
                $this->logger->error( 'Upload failed for file.', [
                    'attachment_id' => $attachment_id,
                    'key'           => $r2_key,
                ] );
            }
        }

        if ( $result['failed'] === 0 ) {
            // Mark synced only when there are no failures.
            // This covers both fresh syncs (uploaded > 0) and re-syncs where everything
            // was already on R2 (uploaded = 0, skipped > 0) — status remains '1'.
            update_post_meta( $attachment_id, '_r2_offload_synced',    '1' );
            update_post_meta( $attachment_id, '_r2_offload_keys',      wp_json_encode( array_values( array_unique( $uploaded_keys ) ) ) );
            update_post_meta( $attachment_id, '_r2_offload_synced_at', time() );
            delete_post_meta( $attachment_id, '_r2_offload_error' );
            delete_post_meta( $attachment_id, '_r2_offload_retry_count' );

            // Track stats only for bytes actually transferred in this call.
            if ( $result['uploaded'] > 0 ) {
                $this->record_stat( $result['uploaded'], $bytes_uploaded );
            }

            // Delete local files if configured — only for files uploaded in this call.
            if ( $this->settings->get_delete_local() && $result['uploaded'] > 0 ) {
                $this->delete_local_files( array_keys( $all_files ) );
            }
        } else {
            $current_retry = (int) get_post_meta( $attachment_id, '_r2_offload_retry_count', true );
            update_post_meta( $attachment_id, '_r2_offload_retry_count', $current_retry + 1 );
            update_post_meta( $attachment_id, '_r2_offload_error', "Uploaded: {$result['uploaded']}, Failed: {$result['failed']}" );
        }

        return $result;
    }

    /**
     * Remove all R2 objects for an attachment and clean up post meta.
     */
    public function desync_attachment( int $attachment_id ): bool {
        $keys_json = get_post_meta( $attachment_id, '_r2_offload_keys', true );
        if ( $keys_json ) {
            $keys = json_decode( $keys_json, true );
            if ( is_array( $keys ) && $keys ) {
                $this->r2->delete_files( $keys );
            }
        }
        delete_post_meta( $attachment_id, '_r2_offload_synced' );
        delete_post_meta( $attachment_id, '_r2_offload_keys' );
        delete_post_meta( $attachment_id, '_r2_offload_synced_at' );
        delete_post_meta( $attachment_id, '_r2_offload_retry_count' );
        delete_post_meta( $attachment_id, '_r2_offload_error' );
        return true;
    }

    // -------------------------------------------------------------------------
    // Private helpers
    // -------------------------------------------------------------------------

    /**
     * Build a [ local_path => r2_key ] map for all files belonging to an attachment.
     * Includes original + every registered image size in $metadata['sizes'],
     * which automatically covers WooCommerce-registered sizes
     * (woocommerce_thumbnail, woocommerce_single, woocommerce_gallery_thumbnail).
     */
    private function collect_files( string $attached, ?array $metadata, string $base_dir, string $path_prefix ): array {
        $files = [];

        // Original file.
        $original_local           = $base_dir . $attached;
        $original_key             = $path_prefix ? "{$path_prefix}/{$attached}" : $attached;
        $files[ $original_local ] = $original_key;

        // All generated sizes — this is where WooCommerce sizes appear.
        if ( ! empty( $metadata['sizes'] ) && is_array( $metadata['sizes'] ) ) {
            // Sizes are stored relative to the original's directory (year/month subdir).
            $subdir = trailingslashit( dirname( $attached ) );
            // Normalise '.' subdir (root-level uploads, no year/month).
            if ( $subdir === './' ) {
                $subdir = '';
            }

            foreach ( $metadata['sizes'] as $size_name => $size_data ) {
                if ( empty( $size_data['file'] ) ) {
                    continue;
                }
                $relative             = $subdir . $size_data['file'];
                $local_path           = $base_dir . $relative;
                $r2_key               = $path_prefix ? "{$path_prefix}/{$relative}" : $relative;
                $files[ $local_path ] = $r2_key;
            }
        }

        return $files;
    }

    /**
     * Delete local files after a confirmed upload.
     */
    private function delete_local_files( array $paths ): void {
        foreach ( $paths as $path ) {
            if ( file_exists( $path ) ) {
                wp_delete_file( $path );
            }
        }
    }

    /**
     * Increment daily upload stats stored in wp_options.
     */
    private function record_stat( int $count, int $bytes ): void {
        $key     = 'r2_offload_stats_' . gmdate( 'Y-m-d' );
        $current = get_option( $key, [ 'uploads' => 0, 'bytes' => 0, 'failures' => 0 ] );
        if ( ! is_array( $current ) ) {
            $current = [ 'uploads' => 0, 'bytes' => 0, 'failures' => 0 ];
        }
        $current['uploads'] += $count;
        $current['bytes']   += $bytes;
        update_option( $key, $current, false );
    }
}
