<?php
namespace R2Offload;

defined( 'ABSPATH' ) || exit;

/**
 * Handles uploading/deleting all files for a single attachment (original + all sizes).
 *
 * WooCommerce compatibility notes:
 *  - WooCommerce registers additional image sizes: woocommerce_thumbnail,
 *    woocommerce_single, woocommerce_gallery_thumbnail. These are generated by WP
 *    into $metadata['sizes'] like any other registered size — collect_files() picks
 *    them up automatically with no special handling needed.
 *  - WooCommerce may regenerate sizes after the initial upload (lazy generation via
 *    wc_product_maybe_generate_image_resize). On re-sync we detect which R2 keys are
 *    genuinely new (not already tracked in _r2_offload_keys) and only upload those.
 *    This avoids redundant PutObject calls on files already in R2.
 *  - filesize() is guarded: if "delete local" is enabled and a file was deleted after a
 *    previous sync, we skip it gracefully rather than throwing a warning.
 */
class AttachmentSync {

    private R2Client    $r2;
    private Settings    $settings;
    private ErrorLogger $logger;

    public function __construct( R2Client $r2, Settings $settings, ErrorLogger $logger ) {
        $this->r2       = $r2;
        $this->settings = $settings;
        $this->logger   = $logger;
    }

    /**
     * Upload all files for an attachment to R2 and update post meta.
     * On re-sync (WooCommerce size regeneration) only genuinely new files are uploaded.
     *
     * @param int $attachment_id
     * @return array{ uploaded: int, failed: int, skipped: int }
     */
    public function sync_attachment( int $attachment_id ): array {
        $result = [ 'uploaded' => 0, 'failed' => 0, 'skipped' => 0 ];

        if ( ! $this->settings->is_configured() ) {
            $this->logger->warning( 'Sync skipped: plugin not configured.', [ 'attachment_id' => $attachment_id ] );
            $result['skipped']++;
            return $result;
        }

        $metadata = wp_get_attachment_metadata( $attachment_id );
        $attached = get_post_meta( $attachment_id, '_wp_attached_file', true );

        if ( ! $attached ) {
            $this->logger->error( 'Sync failed: _wp_attached_file meta missing.', [ 'attachment_id' => $attachment_id ] );
            $result['failed']++;
            return $result;
        }

        // Check excluded MIME types.
        $mime = get_post_mime_type( $attachment_id );
        if ( $mime && in_array( $mime, $this->settings->get_excluded_mime_types(), true ) ) {
            $result['skipped']++;
            return $result;
        }

        $upload_dir  = wp_upload_dir();
        $base_dir    = trailingslashit( $upload_dir['basedir'] );
        $path_prefix = $this->settings->get_path_prefix();

        // Build the full [ local_path => r2_key ] map for this attachment.
        $all_files = $this->collect_files( $attached, $metadata, $base_dir, $path_prefix );

        // Determine which keys are already tracked (from a prior sync).
        // This lets us skip files already on R2 and only upload genuinely new ones
        // (e.g. WooCommerce sizes generated after the original upload).
        $existing_keys_json = get_post_meta( $attachment_id, '_r2_offload_keys', true );
        $existing_keys      = $existing_keys_json ? (array) json_decode( $existing_keys_json, true ) : [];
        $existing_keys_set  = array_flip( $existing_keys );

        $uploaded_keys = $existing_keys; // Carry forward what was already uploaded.
        $bytes_uploaded = 0;

        foreach ( $all_files as $local_path => $r2_key ) {
            // Skip files already confirmed in R2.
            if ( isset( $existing_keys_set[ $r2_key ] ) ) {
                $result['skipped']++;
                continue;
            }

            if ( ! file_exists( $local_path ) ) {
                // File may have been deleted by a previous "delete local" run or simply
                // not generated (e.g. WooCommerce lazy generation not triggered yet).
                $this->logger->warning( 'File missing locally, skipping.', [ 'path' => $local_path ] );
                $result['skipped']++;
                continue;
            }

            $file_mime = mime_content_type( $local_path ) ?: ( $mime ?: 'application/octet-stream' );
            $file_size = filesize( $local_path ); // safe: file_exists() checked above

            $ok = $this->r2->upload_file( $local_path, $r2_key, $file_mime );
            if ( $ok ) {
                $uploaded_keys[] = $r2_key;
                $bytes_uploaded += (int) $file_size;
                $result['uploaded']++;
            } else {
                $result['failed']++;
                $this->logger->error( 'Upload failed for file.', [
                    'attachment_id' => $attachment_id,
                    'key'           => $r2_key,
                ] );
            }
        }

        if ( $result['failed'] === 0 ) {
            // Mark synced only when there are no failures.
            // This covers both fresh syncs (uploaded > 0) and re-syncs where everything
            // was already on R2 (uploaded = 0, skipped > 0) — status remains '1'.
            update_post_meta( $attachment_id, '_r2_offload_synced',    '1' );
            update_post_meta( $attachment_id, '_r2_offload_keys',      wp_json_encode( array_values( array_unique( $uploaded_keys ) ) ) );
            update_post_meta( $attachment_id, '_r2_offload_synced_at', time() );
            delete_post_meta( $attachment_id, '_r2_offload_error' );
            delete_post_meta( $attachment_id, '_r2_offload_retry_count' );

            // Track stats only for bytes actually transferred in this call.
            if ( $result['uploaded'] > 0 ) {
                $this->record_stat( $result['uploaded'], $bytes_uploaded );
            }

            // Delete local files if configured — only for files uploaded in this call.
            if ( $this->settings->get_delete_local() && $result['uploaded'] > 0 ) {
                $this->delete_local_files( array_keys( $all_files ) );
                update_post_meta( $attachment_id, '_r2_offload_local_deleted', '1' );
            }
        } else {
            $current_retry = (int) get_post_meta( $attachment_id, '_r2_offload_retry_count', true );
            update_post_meta( $attachment_id, '_r2_offload_retry_count', $current_retry + 1 );
            update_post_meta( $attachment_id, '_r2_offload_error', "Uploaded: {$result['uploaded']}, Failed: {$result['failed']}" );
        }

        return $result;
    }

    /**
     * Restore all files for a synced attachment from R2 back to the local server.
     * Downloads the original + every tracked size into the correct wp-uploads path.
     * Post meta is updated: _r2_offload_local_deleted is cleared on success.
     *
     * @param int $attachment_id
     * @return array{ restored: int, failed: int, skipped: int }
     */
    public function restore_from_r2( int $attachment_id ): array {
        $result = [ 'restored' => 0, 'failed' => 0, 'skipped' => 0 ];

        if ( ! $this->settings->is_configured() ) {
            $result['skipped']++;
            return $result;
        }

        $keys_json = get_post_meta( $attachment_id, '_r2_offload_keys', true );
        if ( ! $keys_json ) {
            $this->logger->warning( 'Restore skipped: no R2 keys on record.', [ 'attachment_id' => $attachment_id ] );
            $result['skipped']++;
            return $result;
        }

        $r2_keys = json_decode( $keys_json, true );
        if ( ! is_array( $r2_keys ) || empty( $r2_keys ) ) {
            $result['skipped']++;
            return $result;
        }

        $upload_dir  = wp_upload_dir();
        $base_dir    = trailingslashit( $upload_dir['basedir'] );
        $path_prefix = $this->settings->get_path_prefix();
        // Build prefix with trailing slash for stripping.
        $prefix_strip = $path_prefix ? trailingslashit( $path_prefix ) : '';

        foreach ( $r2_keys as $r2_key ) {
            // Derive local path from R2 key by stripping the path prefix.
            $relative   = $prefix_strip ? ltrim( substr( $r2_key, strlen( $prefix_strip ) ), '/' ) : ltrim( $r2_key, '/' );
            $local_path = $base_dir . $relative;

            // If the file already exists locally, skip — nothing to restore.
            if ( file_exists( $local_path ) ) {
                $result['skipped']++;
                continue;
            }

            // Ensure the directory exists.
            $dir = dirname( $local_path );
            if ( ! is_dir( $dir ) ) {
                wp_mkdir_p( $dir );
            }

            $ok = $this->r2->download_file( $r2_key, $local_path );
            if ( $ok ) {
                $result['restored']++;
            } else {
                $result['failed']++;
                $this->logger->error( 'Restore: download from R2 failed.', [
                    'attachment_id' => $attachment_id,
                    'key'           => $r2_key,
                    'local'         => $local_path,
                ] );
            }
        }

        if ( $result['failed'] === 0 && $result['restored'] > 0 ) {
            // Clear the local-deleted flag so URLs fall back to local if CDN is removed.
            delete_post_meta( $attachment_id, '_r2_offload_local_deleted' );
            $this->logger->info( 'Attachment restored from R2.', [
                'attachment_id' => $attachment_id,
                'restored'      => $result['restored'],
            ] );
        }

        return $result;
    }

    /**
     * Restore an attachment from R2, verify local files exist, then delete from R2
     * and clean all sync meta. This fully disconnects the attachment from R2.
     *
     * @return array{ restored: int, failed: int, skipped: int, desynced: bool }
     */
    public function restore_and_desync_attachment( int $attachment_id ): array {
        $restore = $this->restore_from_r2( $attachment_id );
        $result  = array_merge( $restore, [ 'desynced' => false ] );

        if ( $restore['failed'] > 0 ) {
            $this->logger->error( 'Restore & desync aborted: restore had failures.', [
                'attachment_id' => $attachment_id,
                'failed'        => $restore['failed'],
            ] );
            return $result;
        }

        // Verify every R2 key has a corresponding local file before deleting from R2.
        $keys_json = get_post_meta( $attachment_id, '_r2_offload_keys', true );
        $r2_keys   = $keys_json ? (array) json_decode( $keys_json, true ) : [];

        if ( ! empty( $r2_keys ) ) {
            $upload_dir   = wp_upload_dir();
            $base_dir     = trailingslashit( $upload_dir['basedir'] );
            $path_prefix  = $this->settings->get_path_prefix();
            $prefix_strip = $path_prefix ? trailingslashit( $path_prefix ) : '';

            foreach ( $r2_keys as $r2_key ) {
                $relative   = $prefix_strip ? ltrim( substr( $r2_key, strlen( $prefix_strip ) ), '/' ) : ltrim( $r2_key, '/' );
                $local_path = $base_dir . $relative;
                if ( ! file_exists( $local_path ) ) {
                    $this->logger->error( 'Restore & desync aborted: local file missing after restore.', [
                        'attachment_id' => $attachment_id,
                        'expected'      => $local_path,
                    ] );
                    $result['failed']++;
                    return $result;
                }
            }
        }

        $this->desync_attachment( $attachment_id );
        $result['desynced'] = true;

        $this->logger->info( 'Attachment restored and desynced from R2.', [
            'attachment_id' => $attachment_id,
            'restored'      => $restore['restored'],
            'skipped'       => $restore['skipped'],
        ] );

        return $result;
    }

    /**
     * Delete all local files for a synced attachment.
     * Sets _r2_offload_local_deleted = 1 so the status is visible in the UI.
     * Only operates on attachments that are confirmed synced to R2.
     *
     * @param int $attachment_id
     * @return array{ deleted: int, skipped: int }
     */
    public function delete_local_for_attachment( int $attachment_id ): array {
        $result = [ 'deleted' => 0, 'skipped' => 0 ];

        // Safety guard — never delete local files if the attachment is not confirmed synced.
        if ( get_post_meta( $attachment_id, '_r2_offload_synced', true ) !== '1' ) {
            $result['skipped']++;
            return $result;
        }

        $attached = get_post_meta( $attachment_id, '_wp_attached_file', true );
        if ( ! $attached ) {
            $result['skipped']++;
            return $result;
        }

        $metadata   = wp_get_attachment_metadata( $attachment_id );
        $upload_dir = wp_upload_dir();
        $base_dir   = trailingslashit( $upload_dir['basedir'] );

        // Collect local paths the same way collect_files() does.
        $all_files = $this->collect_files( $attached, $metadata, $base_dir, $this->settings->get_path_prefix() );

        $any_local_exists = false;

        foreach ( array_keys( $all_files ) as $local_path ) {
            if ( ! file_exists( $local_path ) ) {
                $result['skipped']++;
                continue;
            }
            $any_local_exists = true;
            wp_delete_file( $local_path );
            $result['deleted']++;
        }

        if ( $result['deleted'] > 0 || ! $any_local_exists ) {
            update_post_meta( $attachment_id, '_r2_offload_local_deleted', '1' );
            $this->logger->info( 'Local files deleted after R2 sync.', [
                'attachment_id' => $attachment_id,
                'deleted'       => $result['deleted'],
                'already_gone'  => ! $any_local_exists,
            ] );
        }

        return $result;
    }

    /**
     * Validate that a pre-uploaded attachment already exists in R2 and mark it synced.
     *
     * Architecture: instead of one HeadObject per file (N×sizes API calls), we issue
     * a single ListObjectsV2 for the attachment's directory prefix, build a key set in
     * memory, then check each expected key against that set — 1 API call per attachment
     * regardless of how many sizes it has.
     *
     * An optional $r2_key_set can be passed when the caller has already fetched the full
     * bucket listing for the prefix (e.g. BatchProcessor pre-fetching a shared year/month
     * directory). When provided, no API call is made at all — just a set lookup.
     *
     * @param int        $attachment_id
     * @param array|null $r2_key_set Flat array of R2 keys already known to exist (keys are values).
     *                               Pass null to trigger a ListObjectsV2 for this attachment's prefix.
     * @return array{ claimed: int, missing: int, skipped: int, missing_keys: string[] }
     */
    public function validate_pre_uploaded( int $attachment_id ): array {
        $result = [ 'claimed' => 0, 'missing' => 0, 'skipped' => 0, 'missing_keys' => [] ];

        // Already synced — nothing to do.
        if ( get_post_meta( $attachment_id, '_r2_offload_synced', true ) === '1' ) {
            $result['skipped']++;
            $this->logger->debug( 'Validate: skipped — already synced.', [ 'attachment_id' => $attachment_id ] );
            return $result;
        }

        if ( ! $this->settings->is_configured() ) {
            $result['skipped']++;
            $this->logger->warning( 'Validate: skipped — plugin not configured.', [ 'attachment_id' => $attachment_id ] );
            return $result;
        }

        $attached = get_post_meta( $attachment_id, '_wp_attached_file', true );
        if ( ! $attached ) {
            $result['skipped']++;
            $this->logger->warning( 'Validate: skipped — _wp_attached_file meta missing.', [ 'attachment_id' => $attachment_id ] );
            return $result;
        }

        $mime = get_post_mime_type( $attachment_id );
        if ( $mime && in_array( $mime, $this->settings->get_excluded_mime_types(), true ) ) {
            $result['skipped']++;
            $this->logger->debug( 'Validate: skipped — excluded MIME type.', [ 'attachment_id' => $attachment_id, 'mime' => $mime ] );
            return $result;
        }

        $metadata    = wp_get_attachment_metadata( $attachment_id ) ?: null;
        $upload_dir  = wp_upload_dir();
        $base_dir    = trailingslashit( $upload_dir['basedir'] );
        $path_prefix = $this->settings->get_path_prefix();

        $all_files = $this->collect_files( $attached, $metadata, $base_dir, $path_prefix );
        $r2_keys   = array_values( $all_files );

        // Check each expected key directly via HeadObject — only the exact keys
        // under the configured prefix are tested, nothing else in the bucket is touched.
        $missing_keys = [];
        foreach ( $r2_keys as $r2_key ) {
            if ( ! $this->r2->file_exists( $r2_key ) ) {
                $missing_keys[] = $r2_key;
            }
        }

        $this->logger->info( 'Validate: checked R2 keys.', [
            'attachment_id' => $attachment_id,
            'checked'       => count( $r2_keys ),
            'missing'       => count( $missing_keys ),
        ] );

        if ( ! empty( $missing_keys ) ) {
            $result['missing']      = count( $missing_keys );
            $result['missing_keys'] = $missing_keys;
            $this->logger->warning( 'Validate: attachment not fully on R2 — missing keys.', [
                'attachment_id' => $attachment_id,
                'missing'       => $missing_keys,
            ] );
            return $result;
        }

        // All keys confirmed in R2 — claim the attachment as synced.
        update_post_meta( $attachment_id, '_r2_offload_synced',    '1' );
        update_post_meta( $attachment_id, '_r2_offload_keys',      wp_json_encode( $r2_keys ) );
        update_post_meta( $attachment_id, '_r2_offload_synced_at', time() );
        delete_post_meta( $attachment_id, '_r2_offload_error' );
        delete_post_meta( $attachment_id, '_r2_offload_retry_count' );

        // Increment the validate-specific claimed counter for accurate UI reporting.
        $claimed_so_far = (int) get_option( 'r2_offload_validate_claimed', 0 );
        update_option( 'r2_offload_validate_claimed', $claimed_so_far + 1, false );

        $this->logger->info( 'Validate: attachment claimed from R2.', [
            'attachment_id' => $attachment_id,
            'file'          => $attached,
            'keys'          => count( $r2_keys ),
        ] );

        $result['claimed']++;
        return $result;
    }

    /**
     * Remove all R2 objects for an attachment and clean up post meta.
     */
    public function desync_attachment( int $attachment_id ): bool {
        $keys_json = get_post_meta( $attachment_id, '_r2_offload_keys', true );
        if ( $keys_json ) {
            $keys = json_decode( $keys_json, true );
            if ( is_array( $keys ) && $keys ) {
                $this->r2->delete_files( $keys );
            }
        }
        delete_post_meta( $attachment_id, '_r2_offload_synced' );
        delete_post_meta( $attachment_id, '_r2_offload_keys' );
        delete_post_meta( $attachment_id, '_r2_offload_synced_at' );
        delete_post_meta( $attachment_id, '_r2_offload_retry_count' );
        delete_post_meta( $attachment_id, '_r2_offload_error' );
        delete_post_meta( $attachment_id, '_r2_offload_local_deleted' );
        return true;
    }

    // -------------------------------------------------------------------------
    // Private helpers
    // -------------------------------------------------------------------------

    /**
     * Build a [ local_path => r2_key ] map for all files belonging to an attachment.
     * Includes original + every registered image size in $metadata['sizes'],
     * which automatically covers WooCommerce-registered sizes
     * (woocommerce_thumbnail, woocommerce_single, woocommerce_gallery_thumbnail).
     */
    /**
     * Public wrapper for the diagnostic tool — exposes collect_files() without
     * making the internal method public (preserves internal call sites unchanged).
     */
    public function collect_files_public( string $attached, ?array $metadata, string $base_dir, string $path_prefix ): array {
        return $this->collect_files( $attached, $metadata, $base_dir, $path_prefix );
    }

    private function collect_files( string $attached, ?array $metadata, string $base_dir, string $path_prefix ): array {
        $files = [];

        // Original file.
        $original_local           = $base_dir . $attached;
        $original_key             = $path_prefix ? "{$path_prefix}/{$attached}" : $attached;
        $files[ $original_local ] = $original_key;

        // All generated sizes — this is where WooCommerce sizes appear.
        if ( ! empty( $metadata['sizes'] ) && is_array( $metadata['sizes'] ) ) {
            // Sizes are stored relative to the original's directory (year/month subdir).
            $subdir = trailingslashit( dirname( $attached ) );
            // Normalise '.' subdir (root-level uploads, no year/month).
            if ( $subdir === './' ) {
                $subdir = '';
            }

            foreach ( $metadata['sizes'] as $size_name => $size_data ) {
                if ( empty( $size_data['file'] ) ) {
                    continue;
                }
                $relative             = $subdir . $size_data['file'];
                $local_path           = $base_dir . $relative;
                $r2_key               = $path_prefix ? "{$path_prefix}/{$relative}" : $relative;
                $files[ $local_path ] = $r2_key;
            }
        }

        return $files;
    }

    /**
     * Delete local files after a confirmed upload.
     */
    private function delete_local_files( array $paths ): void {
        foreach ( $paths as $path ) {
            if ( file_exists( $path ) ) {
                wp_delete_file( $path );
            }
        }
    }

    /**
     * Increment daily upload stats stored in wp_options.
     */
    private function record_stat( int $count, int $bytes ): void {
        $key     = 'r2_offload_stats_' . gmdate( 'Y-m-d' );
        $current = get_option( $key, [ 'uploads' => 0, 'bytes' => 0, 'failures' => 0 ] );
        if ( ! is_array( $current ) ) {
            $current = [ 'uploads' => 0, 'bytes' => 0, 'failures' => 0 ];
        }
        $current['uploads'] += $count;
        $current['bytes']   += $bytes;
        update_option( $key, $current, false );
    }
}
